name: Publish snapshot
on:
  push:
jobs:
  publish:
    name: Public snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup JDK17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'liberica'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build without tests
        run: |
          cd src/calculator
          chmod +x gradlew
          ./gradlew build -x test -x check --no-daemon

      - name: Publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SNAPSHOT: true
        run: |
          cd src/calculator
          ./gradlew publishAllPublicationToGitHubRepository --no-daemon
          
