name: image-dev-push.yml
on:
  push:
    branches: [dev]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-dev
  IMAGE_VERSION: ${{ github.sha }}
  GITHUB_ACTOR: ${{ github.actor }}
  BP_JVM_VERSION: 17
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
jobs:
  push:
    name: Push image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup JDK17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'liberica'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build project
        run: |
          cd src/calculator
          ./gradlew GenerateOpenapiServer
          ./gradlew build \
          -x test -x check

      - name: Build and push OCI image
        run: |
          cd src/calculator
         
          T_REGISTRY=$(echo "$REGISTRY" | tr '[:upper:]' '[:lower:]')
          T_GITHUB_ACTOR=$(echo "$GITHUB_ACTOR" | tr '[:upper:]' '[:lower:]')
          T_IMAGE_NAME=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/-/g' | sed 's/--*/-/g')
          T_IMAGE_VERSION=$(echo "$IMAGE_VERSION" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/-/g') 
          
          ./gradlew bootBuildImage \
          --imageName="$T_REGISTRY/$T_IMAGE_NAME:$IMAGE_VERSION"
          
          docker push "$T_REGISTRY/$T_GITHUB_ACTOR/$T_IMAGE_NAME:$T_IMAGE_VERSION"